import { Generated, Insertable, Selectable, Updateable } from "kysely";

export interface Database {
  groups: GroupsTable;
  passwords: PswdsTable;
  types: TypesTable;
  logins: LoginsTable;
  users: UsersTable;
}

// This interface describes the `person` table to Kysely. Table
// interfaces should only be used in the `Database` type above
// and never as a result type of a query!. See the `Person`,
// `NewPerson` and `PersonUpdate` types below.
export interface GroupsTable {
  // Columns that are generated by the database should be marked
  // using the `Generated` type. This way they are automatically
  // made optional in inserts and updates.
  id: Generated<number>;
  name: string;
  createdAt: number;
  updatedAt: number;
}

// You should not use the table schema interfaces directly. Instead, you should
// use the `Selectable`, `Insertable` and `Updateable` wrappers. These wrappers
// make sure that the correct types are used in each operation.
//
// Most of the time you should trust the type inference and not use explicit
// types at all. These types can be useful when typing function arguments.
export type Group = Selectable<GroupsTable>;
export type NewGroup = Insertable<GroupsTable>;
export type GroupUpdate = Updateable<GroupsTable>;

export interface PswdsTable {
  id: Generated<number>;
  name: string;
  hostDomain: string;
  pass: string;
  groupID: number;
  typeID: number;
  note: string;
  createdAt: number;
  updatedAt: number;
}

export type Pswd = Selectable<PswdsTable>;
export type NewPswd = Insertable<PswdsTable>;
export type PswdUpdate = Updateable<PswdsTable>;

export interface TypesTable {
  id: Generated<number>;
  name: string;
  createdAt: number;
  updatedAt: number;
}

export type Type = Selectable<TypesTable>;
export type NewType = Insertable<TypesTable>;
export type TypeUpdate = Updateable<TypesTable>;

export interface LoginsTable {
  id: Generated<number>;
  firstName: string;
  lastName: string;
  email: string;
  pass: string;
  salt: string;
  createdAt: number;
  updatedAt: number;
}

export type Login = Selectable<LoginsTable>;
export type NewLogin = Insertable<LoginsTable>;
export type LoginUpdate = Updateable<LoginsTable>;

export interface UsersTable {
  id: Generated<number>;
  loginID: number;
  privateKey: string;
  pubKey: string;
  group_id: number;
  groupKey: string;
  salt: string;
  createdAt: number;
  updatedAt: number;
}

export type User = Selectable<UsersTable>;
export type NewUser = Insertable<UsersTable>;
export type UserUpdate = Updateable<UsersTable>;
